# Generated by Django 3.0.6 on 2021-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210215_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(max_length=70),
        ),
    ]
